// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djibnjqtxvefslifgvfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqaWJuanF0eHZlZnNsaWZndmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTkzNjgsImV4cCI6MjA1ODMzNTM2OH0.9ID2qZ78jk32YUr2HVTMW3xSmsrV2smvh1GZEBLBK58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);